# Generated by Django 4.1.2 on 2022-10-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.TextField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('mark', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='parents.parents')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['age'],
            },
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['firstname', 'lastname'], name='first_last_name_index'),
        ),
        migrations.AddConstraint(
            model_name='students',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 5)), name='age greater than 5'),
        ),
    ]
