# Generated by Django 4.1.2 on 2022-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200, unique=True)),
                ('lastname', models.TextField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
