# Generated by Django 4.1.2 on 2022-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Subject',
            field=models.ManyToManyField(null=True, related_name='parents', to='subjects.subjects'),
        ),
    ]
