# Generated by Django 4.1.2 on 2022-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subjects_namse'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='subjects.subjects'),
        ),
    ]
