# Generated by Django 4.1.2 on 2022-10-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='subjects.subjects'),
        ),
    ]
