# Generated by Django 4.1.2 on 2022-10-30 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_remove_parents_named'),
        ('students', '0002_alter_students_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='firstname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='lastname',
            field=models.TextField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter and contain only letters', regex='^[A-Z][a-zA-Z ]*$')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='parents.parents'),
        ),
    ]
