# Generated by Django 4.1.2 on 2022-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['age']},
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('firstname', 'lastname')},
        ),
        migrations.AddIndex(
            model_name='students',
            index=models.Index(fields=['firstname', 'lastname'], name='first_last_name_index'),
        ),
        migrations.AddConstraint(
            model_name='students',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 5)), name='age greater than 5'),
        ),
    ]
