# Generated by Django 4.1.2 on 2022-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('students', '0003_remove_students_subject_students_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Subjects',
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(related_name='parents', to='subjects.subjects'),
        ),
    ]
