# Generated by Django 4.1.2 on 2022-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
