[tool.poetry]
name = "fristapp"
version = "0.1.0"
description = ""
authors = ["waelelsafty07 <waelelsafty07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
