# Generated by Django 4.1.2 on 2022-10-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.TextField(max_length=200)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'parents',
            },
        ),
    ]
